version: '3.8'

services:
  web:
    build: .
    command: >
      powershell -Command "
      python manage.py collectstatic --noinput;
      python -m waitress --host=0.0.0.0 --port=8000 loginapp.wsgi:application
      "
    volumes:
      - type: bind
        source: .
        target: C:\app
      - type: volume
        source: static_volume
        target: C:\app\staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

volumes:
  static_volume: